# Generated by Django 4.1.2 on 2022-12-05 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_niveau_matieres_matiere_niveau'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleve',
            options={'verbose_name_plural': 'Élèves'},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'verbose_name_plural': 'Matières'},
        ),
        migrations.AlterModelOptions(
            name='niveau',
            options={'verbose_name_plural': 'Niveaux'},
        ),
        migrations.AlterField(
            model_name='note',
            name='valeur',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20, 0)]),
        ),
    ]
