# Generated by Django 4.1.2 on 2022-12-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_enseignant_id_alter_matiere_id_alter_niveau_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='matieres',
            field=models.ManyToManyField(editable=False, to='notes.matiere', verbose_name='Matières'),
        ),
    ]
